/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.12
 * Generated at: 2024-09-25 01:13:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.common;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class footer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<!-- BEGIN PRE-FOOTER -->\r\n");
      out.write("<div class=\"pre-footer\">\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<div class=\"row\">\r\n");
      out.write("			<!-- BEGIN BOTTOM ABOUT BLOCK -->\r\n");
      out.write("			<div class=\"col-md-3 col-sm-6 pre-footer-col\">\r\n");
      out.write("				<h2>About us</h2>\r\n");
      out.write("				<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed\r\n");
      out.write("					diam sit nonummy nibh euismod tincidunt ut laoreet dolore magna\r\n");
      out.write("					aliquarm erat sit volutpat. Nostrud exerci tation ullamcorper\r\n");
      out.write("					suscipit lobortis nisl aliquip commodo consequat.</p>\r\n");
      out.write("				<p>Duis autem vel eum iriure dolor vulputate velit esse molestie\r\n");
      out.write("					at dolore.</p>\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- END BOTTOM ABOUT BLOCK -->\r\n");
      out.write("			<!-- BEGIN BOTTOM INFO BLOCK -->\r\n");
      out.write("			<div class=\"col-md-3 col-sm-6 pre-footer-col\">\r\n");
      out.write("				<h2>Information</h2>\r\n");
      out.write("				<ul class=\"list-unstyled\">\r\n");
      out.write("					<li><i class=\"fa fa-angle-right\"></i> <a href=\"#\">Delivery\r\n");
      out.write("							Information</a></li>\r\n");
      out.write("					<li><i class=\"fa fa-angle-right\"></i> <a href=\"#\">Customer\r\n");
      out.write("							Service</a></li>\r\n");
      out.write("					<li><i class=\"fa fa-angle-right\"></i> <a href=\"#\">Order\r\n");
      out.write("							Tracking</a></li>\r\n");
      out.write("					<li><i class=\"fa fa-angle-right\"></i> <a href=\"#\">Shipping\r\n");
      out.write("							&amp; Returns</a></li>\r\n");
      out.write("					<li><i class=\"fa fa-angle-right\"></i> <a href=\"contacts.html\">Contact\r\n");
      out.write("							Us</a></li>\r\n");
      out.write("					<li><i class=\"fa fa-angle-right\"></i> <a href=\"#\">Careers</a></li>\r\n");
      out.write("					<li><i class=\"fa fa-angle-right\"></i> <a href=\"#\">Payment\r\n");
      out.write("							Methods</a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- END INFO BLOCK -->\r\n");
      out.write("\r\n");
      out.write("			<!-- BEGIN TWITTER BLOCK -->\r\n");
      out.write("			<div class=\"col-md-3 col-sm-6 pre-footer-col\">\r\n");
      out.write("				<h2 class=\"margin-bottom-0\">Latest Tweets</h2>\r\n");
      out.write("				<a class=\"twitter-timeline\" href=\"https://twitter.com/twitterapi\"\r\n");
      out.write("					data-tweet-limit=\"2\" data-theme=\"dark\" data-link-color=\"#57C8EB\"\r\n");
      out.write("					data-widget-id=\"455411516829736961\"\r\n");
      out.write("					data-chrome=\"noheader nofooter noscrollbar noborders transparent\">Loading\r\n");
      out.write("					tweets by @keenthemes...</a>\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- END TWITTER BLOCK -->\r\n");
      out.write("\r\n");
      out.write("			<!-- BEGIN BOTTOM CONTACTS -->\r\n");
      out.write("			<div class=\"col-md-3 col-sm-6 pre-footer-col\">\r\n");
      out.write("				<h2>Our Contacts</h2>\r\n");
      out.write("				<address class=\"margin-bottom-40\">\r\n");
      out.write("					35, Lorem Lis Street, Park Ave<br> California, US<br>\r\n");
      out.write("					Phone: 300 323 3456<br> Fax: 300 323 1456<br> Email: <a\r\n");
      out.write("						href=\"mailto:info@metronic.com\">info@metronic.com</a><br>\r\n");
      out.write("					Skype: <a href=\"skype:metronic\">metronic</a>\r\n");
      out.write("				</address>\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- END BOTTOM CONTACTS -->\r\n");
      out.write("		</div>\r\n");
      out.write("		<hr>\r\n");
      out.write("		<div class=\"row\">\r\n");
      out.write("			<!-- BEGIN SOCIAL ICONS -->\r\n");
      out.write("			<div class=\"col-md-6 col-sm-6\">\r\n");
      out.write("				<ul class=\"social-icons\">\r\n");
      out.write("					<li><a class=\"rss\" data-original-title=\"rss\" href=\"#\"></a></li>\r\n");
      out.write("					<li><a class=\"facebook\" data-original-title=\"facebook\"\r\n");
      out.write("						href=\"#\"></a></li>\r\n");
      out.write("					<li><a class=\"twitter\" data-original-title=\"twitter\" href=\"#\"></a></li>\r\n");
      out.write("					<li><a class=\"googleplus\" data-original-title=\"googleplus\"\r\n");
      out.write("						href=\"#\"></a></li>\r\n");
      out.write("					<li><a class=\"linkedin\" data-original-title=\"linkedin\"\r\n");
      out.write("						href=\"#\"></a></li>\r\n");
      out.write("					<li><a class=\"youtube\" data-original-title=\"youtube\" href=\"#\"></a></li>\r\n");
      out.write("					<li><a class=\"vimeo\" data-original-title=\"vimeo\" href=\"#\"></a></li>\r\n");
      out.write("					<li><a class=\"skype\" data-original-title=\"skype\" href=\"#\"></a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- END SOCIAL ICONS -->\r\n");
      out.write("			<!-- BEGIN NEWLETTER -->\r\n");
      out.write("			<div class=\"col-md-6 col-sm-6\">\r\n");
      out.write("				<div class=\"pre-footer-subscribe-box pull-right\">\r\n");
      out.write("					<h2>Newsletter</h2>\r\n");
      out.write("					<form action=\"#\">\r\n");
      out.write("						<div class=\"input-group\">\r\n");
      out.write("							<input type=\"text\" placeholder=\"youremail@mail.com\"\r\n");
      out.write("								class=\"form-control\"> <span class=\"input-group-btn\">\r\n");
      out.write("								<button class=\"btn btn-primary\" type=\"submit\">Subscribe</button>\r\n");
      out.write("							</span>\r\n");
      out.write("						</div>\r\n");
      out.write("					</form>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- END NEWLETTER -->\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- END PRE-FOOTER -->\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
